### PR TITLE
LOK-2724 BE: Implement sorting and pagination at back end for simple monitored Entities.

### PR DESCRIPTION
**Pull request by smunir-onms**
## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2724

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

### CODE REVIEW

**Review by aurang-zeb313 — CHANGES_REQUESTED** [review]
Please add testing screen shots.

**Comment by smunir-onms** [comment]
> Please add testing screen shots.

image
image
image
image

Screenshots added

**Review by aurang-zeb313 — APPROVED** [review]
LGTM

**Review by cgorantla — APPROVED** [review]
LGTM!

**Pull request merged**
