### PR TITLE
BE : LOK : 2751 : Write a mechnisim to delete monitored entity state from inventory and minion for simple detected monitored.

### PR DESCRIPTION
**Pull request by Junaid-Khan-Nant**
## Description
Write a mechnisim to delete monitored entity state from inventory and minion for simple detected monitored .

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2751

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

### CODE REVIEW

**Review by smunir-onms — COMMENTED** [review]
Looks good, please add validation screenshots

**Comment by Junaid-Khan-Nant** [comment]
[Uploading Screencast from 20-08-2024 14:19:36.webm…]()

**Comment by Junaid-Khan-Nant** [comment]
[Uploading Screencast from 20-08-2024 14:19:36.webm…]()

**Comment by Junaid-Khan-Nant** [comment]
[Screencast from 20-08-2024 14:19:36.webm](https://github.com/user-attachments/assets/176d96bb-f293-42bb-b1dc-8c324a297693)

**Comment by smunir-onms** [comment]
LGTM, @aurang-zeb313 @cgorantla please review and approve.

**Review by cgorantla — APPROVED** [review]
LGTM!

**Pull request merged**
