### PR TITLE
HS-1739: fix metric registry and add jmx reporter

### PR DESCRIPTION
**Pull request by freddy61025**
## Jira link(s)
- https://opennms.atlassian.net/browse/HS-1739

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

### CODE REVIEW

**Comment by agalue** [comment]
I tested this via `jconsole`, and seems to be working.

However, I found that Minion offers metrics via `/metrics` on port 8181, but it looks like all are Ignite-related stuff, although related to Dropwizard Metrics. That means there might be a way to expose the JMX metrics through it (as Prometheus metrics), which would be easier to consume and use than `jconsole`.

**Comment by agalue** [comment]
It would be great to have the equivalent metrics at the Minion Gateway level for the Sink Messages (all of them, not just flows). That way, we can compare if what the Gateway receives via Sink matches what the Minion sends through it via gRPC.

**Comment by freddy61025** [comment]
> It would be great to have the equivalent metrics at the Minion Gateway level for the Sink Messages (all of them, not just flows). That way, we can compare if what the Gateway receives via Sink matches what the Minion sends through it via gRPC.

Lets don't make this PR too complex. I have create a separate ticket for it.

**Comment by agalue** [comment]
I never said *this* PR should include the Gateway side, but without it, we're still blind (and won't be able to solve the Flow issues). Also, we need something at the Minion gRPC level (again, not this PR, but still blind without it, as that can also be the source of the problem).

JMX is nice, but not as lovely as Prometheus (yes, it can be another PR; but we should be consistent, I believe).

Finally, when is this going to be merged?

**Review by fooker — APPROVED** [review]

**Pull request merged**
