### PR TITLE
LOK-2519 Generic use of DownloadResponse - Refactoring

### PR DESCRIPTION
**Pull request by Mohammad-Junid**
## Description
 Need to use Generic class DownloadResponse  replacing following Classes;

TopNResponse
DownloadAlertsResponse
IpInterfaceResponse
SnmpInterfaceResponse
SearchEventsResponse

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2519

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

### CODE REVIEW

**Comment by Mohammad-Junid** [comment]
image
image

**Review by smunir-onms — COMMENTED** [review]
LGTM

**Review by aurang-zeb313 — COMMENTED** [review]
LGTM! but you need to test all the use cases and attached screenshots.

**Comment by Mohammad-Junid** [comment]
image
image
image

**Review by aurang-zeb313 — APPROVED** [review]
LGTM

**Pull request merged**
