### PR TITLE
LOK-2237: Add SearchEvents API

### PR DESCRIPTION
**Pull request by aurang-zeb313**
## Description

This is part of events service, need to add a new grpc service in events.proto,  for ex: searchEvents(nodeId, searchTerm).

We should only search for the events in a given node here.

Search should at least include uei, location_name, ip_address, description, log_message

Note that tenantId is always need to be validate for all grpc calls.

Add a test case for this grpc service.

Also add a graphQL service in rest-server ( bff)  and use grpc service added.

## Jira link(s)
https://opennms.atlassian.net/browse/LOK-2237

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

### CODE REVIEW

**Review by smunir-onms — CHANGES_REQUESTED** [review]
LGTM, need to run Spotless

**Review by cgorantla — COMMENTED** [review]
LGTM, can you add SpringBootTest ( in place of CucumberIT for now) to validate this

**Comment by aurang-zeb313** [comment]
> LGTM, can you add SpringBootTest ( in place of CucumberIT for now) to validate this

I have already added spring boot test case for the new grpc service. plz see commit no: b56cfd189f9877b87da1633474b1225a5cc8e132. Plz see last commit in this task.

**Comment by cgorantla** [comment]
> > LGTM, can you add SpringBootTest ( in place of CucumberIT for now) to validate this
> 
> I have already added spring boot test case for the new grpc service. plz see commit no: [b56cfd1](https://github.com/OpenNMS-Cloud/lokahi/commit/b56cfd189f9877b87da1633474b1225a5cc8e132). Plz see last commit in this task.

I want to see an End-to-End test using postgresql container, persist through EventService and then use grpc calls to validate search. let me know if you have any further doubts

**Review by cgorantla — APPROVED** [review]
LGTM!

**Comment by MusaidAli** [comment]
LGTM

**Review by MusaidAli — APPROVED** [review]
LGTM

**Review by smunir-onms — APPROVED** [review]

**Comment by aurang-zeb313** [comment]
merged it

**Comment by aurang-zeb313** [comment]
Merge PR into develop

**Pull request merged**
