### PR TITLE
LOK-2705: Implement Response Time metrics threshold for monitored services.

### PR DESCRIPTION
**Pull request by aurang-zeb313**
## Description
Provide option  to set metrics threshold for the response time of services while creating monitoring policy.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2705

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

### CODE REVIEW

**Comment by aurang-zeb313** [comment]
@cgorantla  i have merged https://github.com/OpenNMS-Cloud/lokahi/pull/2048 in my branch so that i can work on metrics threshold for response time. Please ignore the above mentioned PR code for review.

**Comment by aurang-zeb313** [comment]
Screenshot from 2024-08-15 22-27-30

**Comment by aurang-zeb313** [comment]
Screenshot from 2024-08-15 22-26-50

**Review by smunir-onms — COMMENTED** [review]
LGTM may be spotless requires to be run

**Review by smunir-onms — APPROVED** [review]
Looks good

**Pull request merged**
