### PR TITLE
HS-1714: Integration Test: Portal: Re-naming

### PR DESCRIPTION
**Pull request by bouff**
## Description
- Update automation code to swap out `BTO` instance for `cloud` instance.
- Use IDs in a few more places, preferred to CSS lookups.

## Jira link(s)
- https://opennms.atlassian.net/browse/HS-1714

## Flagged for review
- N/A

## Checklist
* [x] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [x] Appropriate reviewer(s) have been selected.
* [x] Jira issue(s) have been updated to "In Review".
* [ ] ~~Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)~~
* [ ] ~~Documentation has been updated as necessary.~~
* [ ] ~~Notify devops of changes to the Charts~~

### CODE REVIEW

**Comment by bouff** [comment]
Manual (local) tests:

Screenshot 2023-06-13 at 2 01 47 PM
Screenshot 2023-06-13 at 1 59 40 PM
Screenshot 2023-06-13 at 1 57 28 PM
Screenshot 2023-06-13 at 1 52 30 PM
Screenshot 2023-06-13 at 12 37 14 PM
Screenshot 2023-06-13 at 12 32 50 PM

**Comment by jbeuree** [comment]
Nothing related to the renaming or other tidying up in this PR, but I've been questioning why these tests are in this repo as they don't work with Lokahi. Would probably be better off in a more relevant repo.

**Comment by bouff** [comment]
> Nothing related to the renaming or other tidying up in this PR, but I've been questioning why these tests are in this repo as they don't work with Lokahi. Would probably be better off in a more relevant repo.

That's a very good point, the portal test suites here can/should be moved to the existing portal E2E repo.

**Review by vserrago — APPROVED** [review]
Content of the changes LGTM

**Pull request merged**
