### PR TITLE
LOK-1906: Delete monitoring policies UI functionality

### PR DESCRIPTION
**Pull request by mikewrosey**
## Description
Adds trash icons to delete the monitoring policies. 
Icons open a confirmation modal which shows how many alarms are associated with the policy and and asks if the user wishes to proceed.

[screencast-onmshs.local_1443-2023.09.21-15_53_40.webm](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/c1ce4796-f515-4eba-be9c-b45b8601b8e5)

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-1906

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

### CODE REVIEW

**Review by freddy61025 — COMMENTED** [review]
Is there any delete rule function? The way that save policy should not able to remove rule.

**Review by synqotik — APPROVED** [review]
Looks good as far as I can tell, especially the UI. May be some details of policies and rules that I don't know enough about. Freddy's comment should be addressed.

**Comment by mikewrosey** [comment]
> Is there any delete rule function? The way that save policy should not able to remove rule.

You bring up a good point. When we add a rule or modify a rule, Save Policy must be clicked after. I thought it should be the same with deleting a rule, for consistency, but I'm not sure. I know the whole page is being re-designed but I'll run it by Amanda and see what she thinks about deleting the rule without saving the policy after.

**Comment by mikewrosey** [comment]
> > Is there any delete rule function? The way that save policy should not able to remove rule.
> 
> You bring up a good point. When we add a rule or modify a rule, Save Policy must be clicked after. I thought it should be the same with deleting a rule, for consistency, but I'm not sure. I know the whole page is being re-designed but I'll run it by Amanda and see what she thinks about deleting the rule without saving the policy after.

After confirming, I've update this PR to use the `deleteRuleById` and `countAlertByRuleId` api calls!

**Review by freddy61025 — APPROVED** [review]
LGTM

**Pull request merged**
