### PR TITLE
DP-41: DOC: Migrate docs from GitHub wiki

### PR DESCRIPTION
**Pull request by Bonrob2**
## Jira link(s)
- https://opennms.atlassian.net/browse/DP-41

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

### CODE REVIEW

**Comment by Bonrob2** [comment]
@indigo423 would you be able to review this PR? Mainly interested in the structure and that it builds ok. The content is from the Wiki which has been reviewed by several developers. It might not be up to date with some of the more recent changes, but we could create another Jira to review the content.

**Comment by indigo423** [comment]
@Bonrob2 I've seen a branch named [DP-41A](https://github.com/OpenNMS-Cloud/lokahi/tree/DP-41A). Was that a mistake and we can safely delete it?

**Review by indigo423 — COMMENTED** [review]
I've found a little glitch here:

Screenshot 2023-07-04 at 18 41 52

**Comment by Bonrob2** [comment]
> @Bonrob2 I've seen a branch named [DP-41A](https://github.com/OpenNMS-Cloud/lokahi/tree/DP-41A). Was that a mistake and we can safely delete it?

Yes. Thanks. I have deleted it.

**Comment by Bonrob2** [comment]
> I've found a little glitch here:

For the table of contents, I'm not sure what the issue is. If I include the title of the file in the nav (e.g., * xref:installation:installation.adoc[Installation]) the name appears in the TOC. If I don't (e.g., * xref:installation:installation.adoc[]), I get the name of the file.

**Comment by indigo423** [comment]
@Bonrob2 I've fixed the problem in the reference section. The issue was, there is no introduction.adoc file, there is just a glossary.adoc file. I've also removed the public directory from the repository.

I've created a package.json and package-lock.json which allows you to get Antora installed locally with `npm install` and created also a local playbook so you can compile locally immediately with `npx antora --stacktrace generate antora-playbook-local.yml` from the root directory of the repository.

**Review by indigo423 — APPROVED** [review]
Framework wise this looks good to me.

**Comment by Bonrob2** [comment]
@indigo423 . Updated my local environment to ensure that TOC was building correctly, and it is now. No longer getting the .adoc file labels in the TOC.

**Pull request merged**
