### PR TITLE
LOK-2506: SNMP Collector config is not always send on initial discovery

### PR DESCRIPTION
**Pull request by aurang-zeb313**
## Description
Under some unknown circumstances, after discovering a node first time, the SNMP config is not populated correctly and the list of parts to collect is empty. A second discovery makes the datacollection work.

## Jira link(s)
- https://opennms.atlassian.net/browse/LOK-2506

## Checklist
* [ ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts.
* [ ] Notify documentation team of any changes to names of screens or features (affects URLs).

### CODE REVIEW

**Review by cgorantla — COMMENTED** [review]
How does it solve the problem described ?

**Comment by aurang-zeb313** [comment]
> How does it solve the problem described ?

Line updates the node table's system object id. The issue was that the system object id in the node was not modified when we added the node and the SNMP collector task. As a result, the minion received an empty list of parts (the SNMP configuration) and no metrics were gathered. Now when node scanner collect system object id , IP and SNMP  interfaces, first it update the node information and then get SNMP configuration and send to minion. The System Object Id is required for the snmp configuration. I have tested and verified and its working as expected.

**Comment by cgorantla** [comment]
> > How does it solve the problem described ?
> 
> The issue was that the system object id in the node was not modified when we added the node and the SNMP collector task. As a result, the minion received an empty list of parts (the SNMP configuration) and no metrics were gathered. Now when node scanner collect system object id , IP and SNMP interfaces, first it update the node information and then get SNMP configuration and send to minion. The System Object Id is required for the snmp configuration. I have tested and verified and its working as expected.

I understand that part but this is just moving code up/down. Do we know why the current change works ?

**Comment by aurang-zeb313** [comment]
> > > How does it solve the problem described ?
> > 
> > 
> > The issue was that the system object id in the node was not modified when we added the node and the SNMP collector task. As a result, the minion received an empty list of parts (the SNMP configuration) and no metrics were gathered. Now when node scanner collect system object id , IP and SNMP interfaces, first it update the node information and then get SNMP configuration and send to minion. The System Object Id is required for the snmp configuration. I have tested and verified and its working as expected.
> 
> I understand that part but this is just moving code up/down. Do we know why the current change works ?

The system object id was updated after the snmp collector task that sends the snmp configuration to Minion, and it is required for the snmp collector task to submit the snmp configuration to Minion.

**Comment by aurang-zeb313** [comment]
> > > > How does it solve the problem described ?
> > > 
> > > 
> > > The issue was that the system object id in the node was not modified when we added the node and the SNMP collector task. As a result, the minion received an empty list of parts (the SNMP configuration) and no metrics were gathered. Now when node scanner collect system object id , IP and SNMP interfaces, first it update the node information and then get SNMP configuration and send to minion. The System Object Id is required for the snmp configuration. I have tested and verified and its working as expected.
> > 
> > 
> > I understand that part but this is just moving code up/down. Do we know why the current change works ?
> 
> The system object id was updated after the snmp collector task that sends the snmp configuration to Minion, and it is required for the snmp collector task to submit the snmp configuration to Minion.

if still confusion then we can discuss over call?

**Review by cgorantla — APPROVED** [review]
LGTM!

**Pull request merged**
